const currentYear = new Date().getFullYear();
const startingYear = 2003;
const yearsDifference = currentYear - startingYear;

export const questionsData = [
  {
    id: 1,
    question: 'Wie viele Menschen mit Schwerbehinderung leben in Deutschland?',
    answers: [
      {
        id: 1,
        text: '7,8 Millionen',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: '12,5 Millionen',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: '17,5 Millionen',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: '2,7 Millionen',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 2,
    question: 'Was beinhaltet das Konzept leichte Sprache?',
    answers: [
      {
        id: 1,
        text: 'Eine besonders verständliche Sprache in Wort und Schrift für Menschen mit Lernbehinderung',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Eine Sprache, die ohne Grammatik auskommt',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Eine Sprache, die geschrieben auf Großbuchstaben verzichtet',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Eine Sprache, die ohne Rechtschreibung auskommt',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 3,
    question:
      'Szene: Frau im Rollstuhl kommt zu einer Tür. Wie würde sie sich wünschen, dass man ihr begegnet?',
    answers: [
      {
        id: 1,
        text: 'Sie möchte, dass man ihr die Tür aufmacht und sie nicht anspricht',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Sie möchte gefragt werden ob man ihr die Tür aufmachen darf',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Sie möchte ignoriert werden',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Sie möchte, dass man ihr die Tür aufmacht, den Kopf streichelt und sie bemitleidet',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 4,
    question:
      'Szene: Eine Assistentin sitzt mit einem Mann mit Sehbehinderung am Esstisch. Er würde gerne das Salz haben. Wie geht ihr vor?',
    answers: [
      {
        id: 1,
        text: 'Sie gibt ihm das Salz in die Hand',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Sie ergreift sein Handgelenk und führt ihn zum Salz',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Sie legt ihre Hand unter seine und führt ihn zum Salz',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Sie legt ihre Hand auf seine Hand und führt ihn zum Salz',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 5,
    question:
      'Wie heißt die taktile Sprache, mit der taubblinde Menschen kommunizieren?',
    answers: [
      {
        id: 1,
        text: 'Lormen',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Normen',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Formen',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Mormen',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 6,
    question:
      'Wann spricht man von einer psychischen oder seelischen Behinderung?',
    answers: [
      {
        id: 1,
        text: 'Wenn eine psychische Störung bleibt, wird sie zur psychischen Behinderung',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Wenn man für drei Monate nach einer Trennung traurig ist',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Eine psychische Behinderung ist das Erleben einer psychotischen Episode',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Psychisch behindert ist man, wenn man in der Pubertät längere depressive Episoden hatte',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 7,
    question: 'Welche Ursache ist die häufigste für eine Behinderung?',
    answers: [
      {
        id: 1,
        text: 'Schwangerschaft',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Krankheit',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Komplikationen bei der Geburt ',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Unfall',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 8,
    question: 'Was ist eine Induktionsanlage?',
    answers: [
      {
        id: 1,
        text: 'Eine Alarmanlage',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Eine Gegensprechanlage',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Ein Hilfsmittel für gehörlose Menschen ',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Ein elektronischer Herd',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 9,
    question: 'Ab wann gilt eine Person als blind?',
    answers: [
      {
        id: 1,
        text: 'Bei weniger als 50% Sehkraft',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Bei weniger als 25% Sehkraft',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Bei weniger als 15% Sehkraft ',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Bei weniger als 2% Sehkraft',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 10,
    question: 'Was sind keine Merkmale von Lernschwäche?',
    answers: [
      {
        id: 1,
        text: 'Überblick über Abläufe und Prozesse ist schwierig',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Persönlichkeits- oder Verhaltensstörungen',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Orientierung ist erschwert ',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Komplexe Informationen werden nicht verstanden',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 11,
    question:
      'Wie heißt die Weiterbildung zur Assistent*in für Menschen mit Behinderungen von ava?',
    answers: [
      {
        id: 1,
        text: 'avaLearn',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'avaStudy',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'avaSchool',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'avaVersity',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 12,
    question: 'Seit wann gibt es atempo?',
    answers: [
      {
        id: 1,
        text: 'Seit 5 Jahren',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Seit 10 Jahren',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Seit 15 Jahren',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: `Seit ${yearsDifference} Jahren`,
        correct: true,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 13,
    question: 'Wo ist der Sitz von ava?',
    answers: [
      {
        id: 1,
        text: 'Innsbruck',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Wien',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Graz',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Linz',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 14,
    question:
      'Wie heißt die Plattform von ava auf der sich Assistenzsuchende und Assistant*innen verbinden können?',
    answers: [
      {
        id: 1,
        text: 'avaAssist',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'avaAssistenz',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'avaAssistent',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'avaAssissi',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
  {
    id: 15,
    question: 'Was bedeutet der Begriff peer counseling?',
    answers: [
      {
        id: 1,
        text: 'Menschen mit Behinderungen beraten und unterstützen Pädagog*innen in ihrer Arbeit für Menschen mit Behinderungen',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 2,
        text: 'Menschen mit Behinderungen beraten und unterstützen Menschen mit Behinderungen',
        correct: true,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 3,
        text: 'Pädagog*innen beraten und unterstützen Menschen mit Behinderungen',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
      {
        id: 4,
        text: 'Menschen mit Behinderungen beraten und unterstützen Menschen ohne Behinderungen',
        correct: false,
        isChosen: false,
        eliminated: false,
      },
    ],
  },
];
